# Generated by Django 4.0.5 on 2022-07-10 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoEleusisApp', '0003_evento_tiempo_lugar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tiempo',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
