# Generated by Django 4.0.5 on 2022-07-11 00:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoEleusisApp', '0004_alter_tiempo_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tiempo',
            name='evento',
        ),
        migrations.AddField(
            model_name='tiempo',
            name='lugares',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ProyectoEleusisApp.lugar'),
        ),
    ]
