# Generated by Django 4.0.5 on 2022-07-11 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoEleusisApp', '0006_remove_tiempo_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Tiempo',
        ),
    ]
