# Generated by Django 4.0.5 on 2022-07-11 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoEleusisApp', '0007_lugar_fecha_delete_tiempo'),
    ]

    operations = [
        migrations.AddField(
            model_name='lugar',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
