# Generated by Django 4.0.5 on 2022-07-11 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoEleusisApp', '0008_lugar_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='fecha_creacion',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
