# Generated by Django 4.0.5 on 2022-07-11 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoEleusisApp', '0009_evento_fecha_creacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='fecha_creacion',
        ),
        migrations.AddField(
            model_name='evento',
            name='propaganda',
            field=models.BooleanField(default=False),
        ),
    ]
