# Generated by Django 4.0.5 on 2022-07-11 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoEleusisApp', '0013_email_mensaje_alter_email_imagen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
    ]
