# Generated by Django 4.0.5 on 2022-07-16 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoEleusisApp', '0023_alter_evento_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='imagenes/')),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('fk_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ProyectoEleusisApp.evento')),
            ],
        ),
    ]
