# Generated by Django 4.0.5 on 2022-07-16 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoEleusisApp', '0024_inscripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='comprobante',
            field=models.ImageField(upload_to='imagenes/'),
        ),
    ]
