# Generated by Django 4.0.5 on 2022-07-16 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoEleusisApp', '0025_alter_inscripcion_comprobante'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscripcion',
            name='comprobante',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
