# Generated by Django 4.0.5 on 2022-07-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoEleusisApp', '0026_alter_inscripcion_comprobante'),
    ]

    operations = [
        migrations.AddField(
            model_name='inscripcion',
            name='aprobado',
            field=models.BooleanField(default=False),
        ),
    ]
