# Generated by Django 4.0.5 on 2022-08-08 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProyectoEleusisApp', '0027_inscripcion_aprobado'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='precio_dolar',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
